### PR TITLE
Add /labels API to client

### PR DESCRIPTION
**Pull request by jacksontj**
API ref https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names

Signed-off-by: Thomas Jackson <jacksontj.89@gmail.com>

### CODE REVIEW

**Comment by beorn7** [comment]
Note: I plan to cut v1 today. Would be cool to get this in if it is ready for it.

**Comment by krasi-georgiev** [comment]
Thanks!

**Comment by jacksontj** [comment]
@beorn7 as long as we aren't moving this client to GA yet. IMO https://github.com/prometheus/prometheus/issues/5661 should get done first -- so we don't have to do another interface break.

**Comment by beorn7** [comment]
@jacksontj What is GA?
I would like to do v1 of client_golang very soon and not wait for Prometheus v2.11.
The API client will be explicitly excluded from semver guarantees.

**Comment by jacksontj** [comment]
@beorn7 I was referring to making this API client "GA" (meaning it follows the semver stuff) -- I wasn't sure what all was included in a v1 release. So if this API client remains as "experimental" (so we can break the API as needed), I'm fine.

**Pull request merged**
