### PR TITLE
Fix deprecated `NewBuildInfoCollector` API

### PR DESCRIPTION
**Pull request by alissa-tung**
1. Update `examples/random/main.go`: `prometheus.NewBuildInfoCollector` is deprecated. Use `collectors.NewBuildInfoCollector` instead.

### CODE REVIEW

**Review by bwplotka — CHANGES_REQUESTED** [review]
Nice! 

But can we remove `main` binary from this PR? I think it was added by accident.

**Comment by alissa-tung** [comment]
> Nice!
> 
> But can we remove `main` binary from this PR? I think it was added by accident.

sorry i gonna give a fix

**Review by kakkoyun — APPROVED** [review]
LGTM

**Comment by kakkoyun** [comment]
@bwplotka Feel free to merge :)

**Comment by kakkoyun** [comment]
@alissa-tung Would you mind maybe adding comment changes in this PR as well here? https://github.com/prometheus/client_golang/pull/918

**Comment by alissa-tung** [comment]
> @alissa-tung Would you mind maybe adding comment changes in this PR as well here? #918

done

**Comment by kakkoyun** [comment]
@alissa-tung By any chance you forgot to push? I don't see the changes

**Comment by alissa-tung** [comment]
> @alissa-tung By any chance you forgot to push? I don't see the changes

yes, sorry :(

**Comment by alissa-tung** [comment]
> > > @alissa-tung By any chance you forgot to push? I don't see the changes
> > 
> > 
> > yes, sorry :(
> 
> Still the same :/

https://github.com/prometheus/client_golang/pull/1000/commits

i though there are some commit message comment here 🤔  im not native English speaker, im afraid that there is something i misunderstood

**Comment by alissa-tung** [comment]
is [ffd6362](https://github.com/prometheus/client_golang/pull/1000/commits/ffd6362a06df307874df9230b3e9394d9b037523) work as expected?

**Comment by kakkoyun** [comment]
> is [ffd6362](https://github.com/prometheus/client_golang/pull/1000/commits/ffd6362a06df307874df9230b3e9394d9b037523) work as expected?

Yes, thanks :pray:

**Review by kakkoyun — APPROVED** [review]
LGTM

**Pull request merged**
