### PR TITLE
Switch testutil to go-cmp

### PR DESCRIPTION
**Pull request by SuperQ**
### Describe your PR

Remove a dependency by using go-cmp for `testutil.CollectAndCompare()`. Note that the string output of `cmp.Diff()` is non-stable, so users depending on stable `error` strings will nolonger work.

### What type of PR is this?

/kind change

### Changelog Entry
```release-note
Use non-deterministic diff function for testutil.CollectAndCompare()
```

### CODE REVIEW

**Comment by kakkoyun** [comment]
> This is an alternative implementation of #1539

I'd rather accept #1539

**Comment by SuperQ** [comment]
Yea, I figured I would provide both options.

While it's extremely annoying, I find I agree slightly with the opinion that depending on error message exact output is a dangerous.

**Comment by ArthurSens** [comment]
Should we close this one now that #1539 was merged?

**Comment by SuperQ** [comment]
Closing in favor of https://github.com/prometheus/client_golang/pull/1539

**Pull request closed without merging**
