### PR TITLE
Fix race condition with Exemplar in Counter

### PR DESCRIPTION
**Pull request by fstab**
Potential fix for #1145.

Signed-off-by: Fabian Stäber <fabian@fstab.de>

### CODE REVIEW

**Comment by fstab** [comment]
Build fails with
```
Error: File is not `gofumpt`-ed with `-extra` (gofumpt)
```
Was that me, or is that an issue with the build pipeline?

**Review by bboreham — COMMENTED** [review]
Suggest a code comment stating that the ordering is essential, otherwise someone may swap it back.
Or even better, a test.

Also note the linter complained.

**Comment by fstab** [comment]
Thanks Bryan. I added a comment. Not sure why the linter had failed, but now it's green again.

**Review by bboreham — APPROVED** [review]
lgtm

**Review by SD145 — APPROVED** [review]
Last comment

**Pull request merged**
