### PR TITLE
calculate size of headers outside of gorouting

### PR DESCRIPTION
**Pull request by yangyuqian**
@beorn7 

Calculate headers concurrently in `computeApproximateRequestSize` concurrently might lead to crash due to limitation in
hashmap of Go.

For instance, in `src/net/http/httputil/reverseproxy.go`, headers will
be modified to ensure consistency, and if calculate(iterate on) headers
inside a separated goroutine, program will crash due to concurrently
read/write on hashmaps.

```
copiedHeaders := false
for _, h := range hopHeaders {
	if outreq.Header.Get(h) != "" {
		if !copiedHeaders {
			outreq.Header = make(http.Header)
			copyHeader(outreq.Header, req.Header)
			copiedHeaders = true
		}
		outreq.Header.Del(h)
	}
}
```

### CODE REVIEW

**Comment by yangyuqian** [comment]
@beorn7 This PR helps to use prometheus metrics in the reverse proxy I'm working on, and below is the screenshot of error message:

image

**Comment by brian-brazil** [comment]
This bit of the library is deprecated for reasons like this. It's recommended to use the promhttp package.

**Comment by yangyuqian** [comment]
I see, trying the recommend lib instead, thank you!

**Comment by beorn7** [comment]
Indeed. We'll remove this code once 0.9 has been released.

**Comment by yangyuqian** [comment]
Thank you!

**Pull request closed without merging**
