### PR TITLE
Change `*_microseconds` -> `*_seconds`

### PR DESCRIPTION
**Pull request by iamjarvo**
Docs use seconds instead of microseconds. Figured I should change both metrics that use microseconds.

@beorn7

### CODE REVIEW

**Comment by beorn7** [comment]
@iamjarvo thanks for the PR. As @grobie said, it's not enough to just rename the metric name. All the other numbers need to be scaled, too. That affects the buckets, but also the default value of the command line parameters (uniform.domain, normal.domain, normal.mean).

**Comment by iamjarvo** [comment]
No problem. I can follow up with the changes in the coming days

**Comment by beorn7** [comment]
To get this off the table, I'll resolve this in a separate PR.

**Comment by beorn7** [comment]
See https://github.com/prometheus/client_golang/pull/257

**Pull request closed without merging**
