### PR TITLE
Add timestamp support for ConstMetric

### PR DESCRIPTION
**Pull request by simonpasquier**
This PR addresses #187 since @brian-brazil mentioned that staleness handling is now ok.

Eager to hear from @beorn7 too. Maybe you had something else in mind regarding how to expose the timestamps in the client API.

### CODE REVIEW

**Comment by beorn7** [comment]
This looks doable to me. However, the ConstMetric creation is a bit clunky at the moment, and I am planning to redo it completely in v0.10. Thus, my grand plan was to introduce the timestamped metrics at that time, so that we don't introduce something now that we break six months later (or so... my scheduling is unfortunately determined by external factors).

On the other hand, if people really need it _now_ (and possibly also without migrating to v0.10), we can do something like in this PR.

Let's see what others think.

**Comment by brian-brazil** [comment]
OpenMetrics will also break this a bit, as we'll probably want to allow for more resolution than milliseconds there.

**Comment by beorn7** [comment]
I'm currently aiming for aligning the OpenMetrics adjustments with the v0.10 changes.

The questions here really is how much it is worth to have any possibility for timestamped metrics in v0.9 (which will then surely experience a breaking change when moving to the bright new v0.10/OpenMetrics universe).

@simonpasquier is this something you have concrete need for or did you just feel it's low hanging fruit to introduce?

**Comment by simonpasquier** [comment]
I don't have an urgent need for it. I know of some internal projects at $work that would benefit from it but they are still at the prototype stage. Another candidate would be collectd_exporter but as collectd supports Prometheus natively since 5.7 and exposes the timestamps, this isn't a compelling case either.

Personally I'm fine with waiting for 0.10 unless other users need it now.

**Comment by beorn7** [comment]
OK, let's keep this PR open for a while to see if others chime in.

**Comment by luqasn** [comment]
We would really like to use this for some of our custom CloudWatch exporters, as the official `cloudwatch-exporter` now uses `ConstMetric` with timestamps and our own golang-exporters still have the timestamps offset, which makes them weird to work with.

**Comment by beorn7** [comment]
@luqasn OK, you got counted. :o)

Would it be possible for you to just merge this PR into your local fork of client_golang? If there were a handful of people requesting this, I'd consider it valuable to introduce a function now that we will break anyway in v0.10. If it's only you, it might be better in sum if you work from a slightly modified version until v0.10 is there.

**Comment by beorn7** [comment]
OK, let's do it then. However, I have a better idea how to do it in detail. The current PR only handles the "plain" metrics, not histogram or summary. And I'd like to avoid the multiplicity of new functions. Stay tuned for a day or tow, and I'll present an alternative PR.

**Comment by brian-brazil** [comment]
OpenMetrics is going for up to nanosecond resolution, accordingly I'd suggest using a `time.Time`.

**Comment by beorn7** [comment]
I have implemented my idea in #443. Please have a look everybody. I'll close this as superseded.

**Comment by jojimt** [comment]
@beorn7 With this change, it is possible to feed two samples of a series into a collector with two different timestamps. That's quite normal when the timestamp is attached by a hw or driver and there is some kind of buffering before the samples are collected. Is that supported? Or it will result in the "was collected before with the same name and label values" error?

**Comment by beorn7** [comment]
Generally speaking, this is against the scrape model of Prometheus. It might work by accident, but it might as well create an error.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a (closed!) GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jojimt** [comment]
Thanks. I will take it to the mailing list (it was sort of related to the timestamp).

**Pull request closed without merging**
