### PR TITLE
fix: Unset Content-Encoding header when uncompressed

### PR DESCRIPTION
**Pull request by mrueg**
This should fix the bug reported in #1595 as RFC2616 says not to set Content-Encoding header for responses without any encoding.

@ArthurSens @bwplotka

### CODE REVIEW

**Review by ArthurSens — APPROVED** [review]
Nice, I just tested locally and works as before :) Thanks for working on this

I wonder if we want to have a test that verifies that? Or too much?

**Review by bwplotka — APPROVED** [review]
Thanks! I wished we have some safeguard for seeing content-encoding set AND accept-encoding causing us to do some different compression, but this is enough as a quick bug fix. Thanks a lot 💪🏽

**Comment by bwplotka** [comment]
I changed the base to release branch as it has to be fixed there first, do you mind rebasing?

**Comment by bwplotka** [comment]
We also need to add one commit for:
 /VERSION  set to 1.20.2
/CHANGELOG.md section for new release and current bugfix

But I can help do that

**Review by bwplotka — APPROVED** [review]

**Pull request merged**
