### PR TITLE
Add opentracing support for Prometheus client.

### PR DESCRIPTION
**Pull request by tomwilkie**
Basic instrumentation to support clients who want to propagate Opentracing context with this client library.

Should be a noop if clients don't have any Opentracing configured.

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by simonpasquier** [comment]
I guess that Grafana has no problem with it :smirk: but it is worth noting that there are a few other projects importing the `v1` package (see https://godoc.org/github.com/prometheus/client_golang/api?importers) which would have to import these additional dependencies on their next vendoring update. Is that really inconvenient to delegate this instrumentation to the caller? Or create another opt-in package with opentracing support?

**Comment by metalmatze** [comment]
Maybe it's possible to have these few functions calls as an local interface? :thinking: 
People could then decide on their own what to pass.

**Comment by tomwilkie** [comment]
@simonpasquier I think thats a reasonable request, let me look into it.

**Comment by tomwilkie** [comment]
Yeah we can do this all in our own code with no modification needed.

**Pull request closed without merging**
