### PR TITLE
Add structured logging support to promhttp

### PR DESCRIPTION
**Pull request by SuperQ**
In order to better support the standard library `log/slog` add a new interface to the `promhttp` `HandlerOpts`.

### CODE REVIEW

**Comment by SuperQ** [comment]
We might want to split out the Go version change into a separate PR.

**Comment by SuperQ** [comment]
Ok, yaks shaven, this is ready to go.

**Comment by SuperQ** [comment]
Seems like dagger is a bit of technical debt for keeping Go versions up to date as well.

**Comment by ArthurSens** [comment]
Hmmm, feels strange that we have 2 loggers in the struct now. I'm assuming this is needed somewhere in a different package/repository, could you clarify how you're planning to use this?

**Comment by tjhop** [comment]
> Hmmm, feels strange that we have 2 loggers in the struct now. I'm assuming this is needed somewhere in a different package/repository, could you clarify how you're planning to use this?

@SuperQ we're only ever logging at `error` level here -- maybe we just lean on slog's built in stdlog adapter and avoid the change here altogether? Something like this:

```go
	// make logger with promslog like normal
	slogger := promslog.New(&promslog.Config{})
	// make stdlog adapter from slogger
	logger := slog.NewLogLogger(slogger.Handler(), slog.LevelError)
```

Bonus points -- log output is still structured

**Comment by SuperQ** [comment]
Yea, I suppose using a stdlib adapter would be fine.

**Pull request closed without merging**
