### PR TITLE
add lock for value operation.

### PR DESCRIPTION
**Pull request by zhanglp92**
When I concurrent running program, has some wrong. I don‘t use metex with my code.
I think locks should be added here.

### CODE REVIEW

**Comment by metalmatze** [comment]
Is this still necessary when using [atomic](https://golang.org/pkg/sync/atomic/) :thinking:

**Comment by grobie** [comment]
No. client_golang is concurrency safe and uses the atomic package to reduce the footprint. Mutex are not only unnecessary here, they would incur a huge performance penalty.

Björn gave a talk explaining the design at the GopherCon 2015, here are the [slides](https://docs.google.com/presentation/d/1T_wdd2KGOPEBhHN6ubendIi87RhtadHOOSAwK0M-Exs/edit?usp=sharing).

**Comment by beorn7** [comment]
The only concurrency issue I know of is https://github.com/prometheus/client_golang/issues/275 (for which I have a solution in my head, I just need to find time to write it down).

**Comment by zhanglp92** [comment]
If you do not use the lock, there will be concurrency issue. 
eg: I concurrent implementation of the program.

func test() {
    gauge.Inc()
    defer gauge.Dec()
}

image

**Comment by beorn7** [comment]
Could you provide the full code to replicate the problem? The above is not sufficient to do that.

**Pull request closed without merging**
