### PR TITLE
/api/v1/rules: alert value as string

### PR DESCRIPTION
**Pull request by holycheater**
a follow-up on https://github.com/prometheus/prometheus/pull/5582

### CODE REVIEW

**Comment by beorn7** [comment]
The Prometheus change will be in 2.10. We should get a release of client_golang done at about the same time as the final 2.10.0 release.

**Comment by daenney** [comment]
2.10-rc0 got tagged today

**Comment by beorn7** [comment]
The final release will happen in three days at the earliest.

**Comment by beorn7** [comment]
@krasi-georgiev Does this look good to you?

**Comment by beorn7** [comment]
Once we have @krasi-georgiev 's LGTM, we'll merge this.

**Pull request merged**
