### PR TITLE
Make Registry public

### PR DESCRIPTION
**Pull request by tsenart**
This change set exports a Registry interface implemented by the local
registry type. I added TODO comments along the way with improvements
that could be done to reduce the surface area of a Registry's behaviour
and to make the code more orthogonal overall. I'd be glad to contribute
these changes over time, if you like the direction I propose.

This has been done on top of the `standard-exports` branch.

All tests pass except for the Linux specifc `/proc` related tests. I
suggest that we add linux specific build tags to those files.

### CODE REVIEW

**Comment by beorn7** [comment]
This PR intentionally left open as a starting point for a future public Registry interface.

**Comment by DBarney** [comment]
Has there been any movement on this? I just realized today that I need to create two endpoints for prometheus to scrape...

**Comment by cagedmantis** [comment]
@beorn7 Has there been any further development along these lines? Do you need somebody to pick up this pr or use this pr as a base to attempt this work again?

**Comment by beorn7** [comment]
Work is in progress. I'm sorry for the lack of speed but higher priority issues kept interfering.

**Comment by beorn7** [comment]
Superseeded by #214.

**Pull request closed without merging**
