### PR TITLE
✏️ [collectors]: fix typo in test assertion

### PR DESCRIPTION
**Pull request by vegerot**

### CODE REVIEW

**Comment by vegerot** [comment]
found while investigating #1135

**Comment by bboreham** [comment]
I know it's annoying, but to merge this we need you to change the commit message to match the "DCO" rule.
https://github.com/prometheus/client_golang/pull/1153/checks?check_run_id=9150113105

**Review by bwplotka — APPROVED** [review]
LGTM, thanks just DCO.

**Comment by vegerot** [comment]
@bboreham what should I make the commit message?

**Comment by bboreham** [comment]
```
[collectors]: fix typo in test assertion

Signed-off-by: Max Coplan <youremail@example.com>
```

**Comment by vegerot** [comment]
> [collectors]: fix typo in test assertion
> 
> Signed-off-by: Max Coplan <youremail@example.com>

done!

**Comment by bwplotka** [comment]
Still DCO is struggling. Do you mind rebasing the PR and singing all commits?

**Comment by bboreham** [comment]
The explanation given at the end of "details" is:
Expected "Max 👨🏽‍💻 Coplan [Max.Coplan@walmart.com](mailto:Max.Coplan@walmart.com)", but got "Max Coplan [mchcopl@gmail.com](mailto:mchcopl@gmail.com)>".

The author in the commit must match the author who signs it off.

**Comment by bboreham** [comment]
@vegerot do you have any New Year energy to engage with the demands of the bot?

**Comment by vegerot** [comment]
@bboreham how's this?

off-topic: am I unusually stubborn, or is this a common barrier preventing people from contributing?

**Comment by bboreham** [comment]
Bot is still complaining.  You can see what it said at the 'Details' link (though I don't really understand it.)

I was able to click on "Set DCO to pass", which I think is OK because I can't see anything wrong with the sign-off.

Now we have a complaint from CircleCI, which is weird because other PRs worked an hour ago.
I tried logging out and in again as it suggested.

@bwplotka any ideas?

**Comment by vegerot** [comment]
@bboreham @bwplotka  sup?

**Comment by bwplotka** [comment]
Can you please rebase if you still want to have this merged? Sorry for lag!

**Comment by vegerot** [comment]
@bwplotka done

**Comment by bwplotka** [comment]
Thanks!

**Pull request merged**
