### PR TITLE
Fix go_collector_latest_test Fail on go1.19

### PR DESCRIPTION
**Pull request by rogerogers**
Fix go_collector_latest_test Fail on go1.19
#1135 

Signed-off-by: rogerogers <rogers@rogerogers.com>

### CODE REVIEW

**Comment by dswarbrick** [comment]
When this is merged, it would be nice to also update the circleci config to actually _test_ with Go 1.19 (as the release notes state).

**Comment by kakkoyun** [comment]
> When this is merged, it would be nice to also update the circleci config to actually _test_ with Go 1.19 (as the release notes state).

When the latest minor release was published, Go 1.19 wasn't officially released, thus the metrics are not the latest file and the CI hasn't added Go 1.19 stage. We will add the support with the upcoming release.

**Review by kakkoyun — COMMENTED** [review]
LGTM. Thanks for adding these regression tests. 
For completeness' sake could you add a test for 1.18?

And I will go ahead and land support for Go 1.19 in a separate PR. Could rebase this PR after it's merged?

**Comment by kakkoyun** [comment]
ref: https://github.com/prometheus/client_golang/pull/1160

**Comment by kakkoyun** [comment]
> LGTM. Thanks for adding these regression tests. For completeness' sake could you add a test for 1.18?
> 
> And I will go ahead and land support for Go 1.19 in a separate PR. Could rebase this PR after it's merged?

Nevermind. Let's do this the other way around.

**Comment by kakkoyun** [comment]
I decided to merge this and base the other PR on these changes.

**Pull request merged**
