### PR TITLE
Fix race condition in writePB().

### PR DESCRIPTION
**Pull request by juliusv**
The RLock already needs to be acquired when reading r.dimHashesByName.

This fixes https://github.com/prometheus/client_golang/issues/61

@beorn7 @stapelberg

### CODE REVIEW

**Comment by grobie** [comment]
What about adding the referenced example to the test suite to ensure concurrent/later registration of metrics work and race conditions can be checked for with the test suite?

**Comment by juliusv** [comment]
@grobie I could add a test case, but don't know a way to test the race directly. I'd have to add a separate Makefile step to run that specific test with the race detector enabled. Is that worth it? I think if we have races again, it would be much more likely a *different* race that that particular test wouldn't catch anyways, and it's not possible to run the whole test suite with `-race` enabled because it uses too much RAM.

**Comment by beorn7** [comment]
:+1:

**Comment by beorn7** [comment]
@grobie @juliusv In principle, think it makes sense to add a test for it, and then mention in the doc string that it can be run with `-race` to test for races. We have a similar case in `prometheus/prometheus/storage/local`. The test would be able to detect some other races, too, especially if it's a bigger fuzz test of some kind.

We can do that later, though.

**Pull request merged**
