### PR TITLE
Add Set() method on counter

### PR DESCRIPTION
**Pull request by sylr**
don't have much hope you'll merge that but I tought i'd try anyway.

### CODE REVIEW

**Comment by brian-brazil** [comment]
You might want to look at https://www.robustperception.io/setting-a-prometheus-counter

**Comment by sylr** [comment]
Yeah I know but for a project I took the party to compute metrics asynchronously to the scrapes cause the whole process might take a while (I know this is not recommended but it's how I did it).

**Comment by beorn7** [comment]
This is breaking the interface and against the general [client library guidelines](https://prometheus.io/docs/instrumenting/writing_clientlibs/).

If you have new arguments to add to the debate, please discuss those on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) as this affects more than just this repo.

**Comment by beorn7** [comment]
In addition to Brian's hint, you can also have a look at https://godoc.org/github.com/prometheus/client_golang/prometheus#CounterFunc

**Pull request closed without merging**
