### PR TITLE
Add Go 1.14

### PR DESCRIPTION
**Pull request by beorn7**
I have also finally added the webhook to activate CircleCI. Let's see how it goes.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1: 

Do we need to do anything over in common for this?

**Comment by beorn7** [comment]
> Do we need to do anything over in common for this?

I guess prometheus/common should also update its testing to 1.14. But that's not tied closely to this change.

**Comment by beorn7** [comment]
CircleCI still not running. Have added deploy key now.

**Comment by beorn7** [comment]
Sooo, apparently the project needs at least one follower to work. Obvious, isn't it? /-:

**Comment by beorn7** [comment]
Cool. It worked.

**Comment by simonpasquier** [comment]
@beorn7 thanks for completing the last mile with Circle CI :)

I've just submitted https://github.com/prometheus/common/pull/232 to enable Circle CI for the common repository as well as adding Go 1.14.

**Pull request merged**
