### PR TITLE
Correct spelling: possibilites -> possibilities

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Review by beorn7 — APPROVED** [review]
Thank you.

**Review by beorn7 — CHANGES_REQUESTED** [review]
However, you need to do the DCO thing, even for a one-letter change, sorry.

**Comment by beorn7** [comment]
See https://github.com/prometheus/client_golang/pull/819/checks?check_run_id=1469673696

**Comment by jubalh** [comment]
Sorry, I forgot to sign the commit. Should be fixed now!

**Review by beorn7 — APPROVED** [review]
\o/

**Pull request merged**
