### PR TITLE
changed the name of all variables with min/max name

### PR DESCRIPTION
**Pull request by parthlaw**
- Renamed variables with name `min`/`max` since go now includes `min` and `max` in the list of [predeclared identifiers](https://go.dev/ref/spec#Predeclared_identifiers)
- Solves issue #1604

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
Thanks!

**Comment by ArthurSens** [comment]
Thanks! Could you also remove these lines and make sure our linter is happy with your changes?

https://github.com/prometheus/client_golang/blob/ffc4cc6470b3c12d9737158212f87dbe4dc9cf19/.golangci.yml#L69-L70

**Comment by parthlaw** [comment]
> Thanks! Could you also remove these lines and make sure our linter is happy with your changes?
> 
> https://github.com/prometheus/client_golang/blob/ffc4cc6470b3c12d9737158212f87dbe4dc9cf19/.golangci.yml#L69-L70

Removed the conditions. Please review the PR again.

**Review by SuperQ — APPROVED** [review]
Nice work.

**Pull request merged**
