### PR TITLE
Export gatherers and registerer of pusher

### PR DESCRIPTION
**Pull request by nghialt**
Hi beorn@soundcloud.com,

I have a need to export `gatherers` and `registerer` of Pusher struct. Please review and comment

Regards,
NghiaLT.

### CODE REVIEW

**Comment by bwplotka** [comment]
Can we learn more about the need? Use cases? (: @nghialt

**Comment by beorn7** [comment]
I have fought very hard to keep the still quite large number of exported types and methods at bay in client_golang to make it less confusing to use. This PR would defeat that purpose. There needed to be a _really_ good reason to do so.

**Comment by nghialt** [comment]
@bwplotka @beorn7 my case is to use `Handler` together with `Pusher`, but `registerer` and `gatherers` are not exported to use in `HandlerFor`

**Comment by beorn7** [comment]
The suggested flow here would be to maintain your registry normally and then expose it with `promhttp.HandlerFor` and push it with `push.Pusher.Gatherer`.

**Comment by beorn7** [comment]
I assume this is clarified sufficiently now.

If you still have questions, I recommend to use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users), where more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Pull request closed without merging**
