### PR TITLE
Document the issues of InstrumentHandler

### PR DESCRIPTION
**Pull request by beorn7**
Obvious next step: Fix those issues. (Which I'm already working on.)

@raliste This at least documents what you have run into in #200 .

### CODE REVIEW

**Comment by raliste** [comment]
Thank you @beorn7 

I'll use direct instrumentation with request timing in the mean time.

**Comment by beorn7** [comment]
We need to fix the CI tests... unrelated to this (doc-comment only) change, though. Merging...

**Comment by F21** [comment]
@beorn7 Sorry for going a bit off topic, but is there any progress on fixing the InstrumentHandler? I am happy to help if needed :smile:

**Comment by beorn7** [comment]
I recommend explicit instrumentation for now. There is no easy "fix" for the issues of `InstrumentHandler`. The problem has to be approached from a very different angle, which I'm working on. Explaining the context for that would take longer than implementing it myself.

**Comment by F21** [comment]
Cool :smile: Looking forward to seeing your implementation. If you need any help, let me know!

**Pull request merged**
