### PR TITLE
Cut 1.19.1

### PR DESCRIPTION
**Pull request by lukasauk**
Cherry-picked two dependabot commits to apply security patches, did not update changelog since it has no user impacting changes.

### CODE REVIEW

**Comment by lukasauk** [comment]
@ArthurSens @bwplotka @kakkoyun

**Comment by kakkoyun** [comment]
@lukasauk, first and foremost, thank you for taking the initiative to open this pull request.  

Typically, a maintainer manages the release process to ensure consistency and alignment with the project's roadmap. Additionally, we tend to reserve minor releases for situations of urgency, such as critical bug fixes or addressing high-severity security vulnerabilities. 

Could you share more details about the objectives you aim to achieve with this release?

**Comment by lukasauk** [comment]
What a warm welcome, @kakkoyun, basically would like to resolve security vulnerabilities on my repositories, thought if the next minor or major will come after a while, would be nice to have a patch for that. But totally understood your point, for reserving patches for more critical occasions.

**Review by bwplotka — APPROVED** [review]
Thanks! This makes sense, sorry for massive lag.

**Comment by bwplotka** [comment]
Sucks we missed this, added issue to track automation to get dependabot on latest releases.

**Comment by bwplotka** [comment]
Released: https://github.com/prometheus/client_golang/releases/tag/v1.19.1

Thanks!

**Comment by bwplotka** [comment]
Hm.. did intent to upgrade `x/net` not x/sys (no alert for it https://github.com/prometheus/client_golang/pull/1459, but for x/net there was https://github.com/prometheus/client_golang/pull/1502)

I think we need to release v1.19.2 now with https://github.com/prometheus/client_golang/pull/1502 (:

**Comment by bwplotka** [comment]
Automation would massively help https://github.com/prometheus/client_golang/issues/1512

**Comment by lukasauk** [comment]
@bwplotka yeah, created this PR before 1502 looks like, but I do really appreciate that you released a minor with security patches, was waiting for that 💜

**Pull request merged**
