### PR TITLE
go.mod: Set minimal support version of go to 1.15

### PR DESCRIPTION
**Pull request by mrueg**
As requested in https://github.com/prometheus/common/pull/353#discussion_r793113705

### CODE REVIEW

**Comment by beorn7** [comment]
Since this library is so widely used, we usually only bump the version requirement if we really have to (i.e. because there is code requiring the more recent version). Supporting the last two or three Go versions is a _minimal_ requirement (i.e. we would use build tags and such for features requiring newer Go versions). As long as older Go versions still work without additional hassle, we should IMHO keep the support.

**Comment by mrueg** [comment]
Thanks for the feedback. Unfortunately I believe it needs to be raised due to the x/net dependency upgraded in https://github.com/prometheus/common/pull/348 to mitigate a potential vuln. With the upgraded x/net, prometheus/common doesn't seem to work with earlier versions of go than 1.15.

@roidelapluie and @SuperQ can chime in, in which order the change should enter as this repo also depends on prometheus/common.

**Comment by beorn7** [comment]
OK, a security update of a dependency, thereby having dependencies requiring newer Go versions, sounds like a good reason.

That context wasn't clear to me.

**Comment by mrueg** [comment]
Apologies again for not providing that context earlier. 
Still not sure how releasing both repos usually works because of the circular dependency. I guess client_golang starts first, then common depends on the new version and then client_golang has another release?

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by SuperQ** [comment]
I'm not sure we need to cut a release for these changes.

**Comment by SuperQ** [comment]
I've updated the branch protection rules to reflect this change.

**Review by kakkoyun — APPROVED** [review]
LGTM 

Thanks for taking care of it.

**Pull request merged**
