### PR TITLE
Update dependencies

### LINKED ISSUE #642: Windows API change on GetCurrentProcess is breaking the lib
On windows 10, just get the last release: 
> go get github.com/prometheus/client_golang/prometheus/promauto
> C:\...\github.com\prometheus\client_golang\prometheus\process_collector_windows.go:78:9: assignment mismatch: 2 variables but "golang.org/x/sys/windows".GetCurrentProcess returns 1 values

It seems related to this change: https://github.com/golang/sys/commit/2dccfee4fd3e23e10ba17b9d696cf2388c28764b
There are other lib broken because of this change: https://github.com/golang/go/issues/34461

go version go1.12.4 windows/amd64

### PR DESCRIPTION
**Pull request by beorn7**
This should happen now and then anyway, but in this case, it should
also fix #642.

Signed-off-by: beorn7 <beorn@grafana.com>

### CODE REVIEW

**Comment by beorn7** [comment]
@alexvaut @zshearin @anjiawei1991 @Stebalien does this help you for #642?

**Comment by Stebalien** [comment]
Updating to the latest sys and crypto fixes the issue for me.

**Comment by anjiawei1991** [comment]
> Updating to the latest sys and crypto fixes the issue for me.

Me too

**Comment by beorn7** [comment]
@krasi-georgiev or @simonpasquier could you approve?

**Comment by brian-brazil** [comment]
:+1:

**Comment by krasi-georgiev** [comment]
LGTM

**Pull request merged**
