### PR TITLE
Auto-update Go Collector Metrics for new Go versions

### PR DESCRIPTION
**Pull request by SachinSahu431**
This PR enables autogeneration of Go Collector metrics for supported Go versions. 

Runnig `make generate-go-collector-test-files` command will generate the required metrics collected by Go Collector for list of Go versions specified in `supported_go_versions.txt`. 

Details about the autogenerated files:
- `prometheus/gen_go_collector_metrics_set.go` will generate `go_collector_metrics_<version>_test.go` file.
- `prometheus/collectors/gen_go_collector_set.go` will generate `go_collector_<version>_test.go` file.

Subsequent PR will include automatic generation of files when a new Go version is released. Plan is to have a weekly scheduled GitHub action that will check for the release of new Go versions and will open a PR with autogenerated required files.

### CODE REVIEW

**Review by ArthurSens — COMMENTED** [review]
Awesome job! 👏 👏 👏 

I've made a few comments but it's already pretty much ready. I'd suggest we introduce the workflow automation in a separate PR, that way we can keep PRs small and easier to review

**Comment by ArthurSens** [comment]
Also, you can fix the linting issues of the failed CI by running `make fmt`

**Comment by SachinSahu431** [comment]
Thank you for the feedback @ArthurSens! I've updated the code and fixed linting issues :)

**Review by kakkoyun — APPROVED** [review]
Awesome 🏆 🥇 💯

**Review by bwplotka — APPROVED** [review]
Thanks 💪🏽

**Pull request merged**
