### PR TITLE
Make use of pre-existing context in InstrumentRoundTripperTrace

### LINKED ISSUE #580: Request context is overridden in instrumented http clients
It is quite common for golang http clients to make use of the `context` package. Example use cases are to halt stalled requests or shutdown appropriately for example. When an application uses the `github.com/prometheus/client_golang/prometheus` package to instrument an http client for metrics, it expects the transport wrappers to preserve the behavior and state of the wrapped client.   

However, what happens with a request context set before the instrumentation of the client is that it gets [replaced by the default root context](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client.go#L216)  and that makes quite of a difference:
```
r = r.WithContext(httptrace.WithClientTrace(context.Background(), trace))
```
From the [golang docs](https://golang.org/pkg/net/http/#Request.WithContext): 
"WithContext returns a shallow copy of r **with its context changed to ctx.**"

The effect is that if you created a context with, for example, `context.WithTimeout` and set it to a `http.Client` (`client.WithContext(ctx)`), and then instrument the client, for example as suggested [here](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client_test.go#L107-L186), and then send requests to a server that is slow enough to trigger timeout, the timeout will never occur.

What is expected instead is that the [`InstrumentRoundTripperTrace`](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client.go#L136) function respects existing request context, if any.

All findings are wrt [`v0.9.2`](https://github.com/prometheus/client_golang/blob/v0.9.2/prometheus/promhttp/instrument_client.go) and [`master`](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client.go).

### PR DESCRIPTION
**Pull request by beorn7**
Fixes #580

@shturec does this do the trick?

### CODE REVIEW

**Comment by shturec** [comment]
Yep, seems ok to me. 
I didn't see you have made a PR already and shot my own (#584) and I've contributed two tests inside that used to verify the behavior with context (using timeout context for the experiment). They work also with your solution so I think it's fine. 
Feel free to make use of them if you find them ok.

**Comment by beorn7** [comment]
Thanks. Having tests for this is great. However, we don't want to pull in a dependency just for assertion. If you don't mind, I will just incorporate the essence of your tests into this PR.

**Comment by beorn7** [comment]
I think I got it all nicely packaged up.

**Comment by beorn7** [comment]
Incidentally, this also fixes the 1st flaky test mentioned in #573

**Pull request merged**
