### PR TITLE
ADD example to query Prometheus HTTP API using client_golang

### PR DESCRIPTION
**Pull request by prakashmishra1598**
Added an example go file to demonstrate querying the Prometheus HTTP API using 'client_golang' (#194)

### CODE REVIEW

**Comment by beorn7** [comment]
Thanks for your contribution.

Since this cannot run on its own (it needs a running Prometheus server and some code changes to make it work), perhaps it would be better to create an example as part of the package doc comment so that it shows up on https://godoc.org/github.com/prometheus/client_golang/api or https://godoc.org/github.com/prometheus/client_golang/api/prometheus/v1 ? See how it is done for https://godoc.org/github.com/prometheus/client_golang/prometheus . 

(As a counter example for stand-alone examples, the examples for the instrumentation client in the `/examples/` dir can just be `go run` and will then server metrics to look at or even point a Prometheus server at it.)

@krasi-georgiev What do you think?

**Comment by prakashmishra1598** [comment]
@beorn7 @krasi-georgiev Yes, having a godoc example makes more sense. I'll add that instead ASAP :)

**Comment by beorn7** [comment]
Thanks.

**Comment by itaysk** [comment]
Just wanted to say this was helpful to me. Thanks @prakashmishra1598 for making the example, and I wish this was more discoverable then in a closed PR. (didn't find in godoc)

**Comment by beorn7** [comment]
That's because it hasn't been added to godoc yet. The godoc beneath the `api` dir could use some love. PRs welcome.

**Comment by AntonioBusillo** [comment]
+1

**Pull request closed without merging**
