### PR TITLE
Remove client_golang/model dependency from text package

### PR DESCRIPTION
**Pull request by fabxc**
@brian-brazil @juliusv @beorn7 

As for the instrumentation package the constants are well defined and stable, so replicating is fine. The label set hashing is internal to the package, so it doesn't have to be identical with anything else. Thus, replicating the hashing code is worth dropping the dependency.

With that the instrumentation package no longer depends on client_golang/model at all. Neither does the Prometheus server.

Is there any other place using it? Otherwise we should delete it soon.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
:+1: but `migrate`, `pushgateway`, and `statsd_bridge` still have this dependency and need to be updated first.

**Comment by juliusv** [comment]
(at least the latter two, which don't use vendoring yet)

**Comment by beorn7** [comment]
@fabxc Is that update of other repos still ongoing?

**Comment by fabxc** [comment]
Theorey yes, practically, not gotten anywhere close to it. `migrate` is wasted effort, though and has it vendored.

**Comment by beorn7** [comment]
We'll actually move everything over from `client_golang/text` to `common/expfmt`. Then the whole text package can be deleted.

In other words: This is obsolete.

**Pull request closed without merging**
