### PR TITLE
[WIP] Convert exposition format to proto3.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
The CI fails because this depends on https://github.com/prometheus/common/pull/52, which in turn depends on this change here. The two repos import each other circularly :-/

**Comment by fabxc** [comment]
Merging the common PR did not make this one pass.

**Comment by juliusv** [comment]
Right, I should have mentioned that it also depends on https://github.com/prometheus/client_model/pull/14.

**Comment by beorn7** [comment]
Looks good, but all of this has to be changed anyway once the proto3 approach is finalized.

**Comment by juliusv** [comment]
Yep, I changed the PR title to [WIP] for now so that nobody accidentally merges it before I restart all the proto3 stuff with the new insights.

**Comment by beorn7** [comment]
I think the proto3 story (and the protobuf story as a whole) needs to be rewritten. I'll close this PR for now.

**Pull request closed without merging**
