### PR TITLE
add start/end parameter for LabelNames

### LINKED ISSUE #766: v1/api.go/LabelNames missing start/end time parameter
Hi
in the file `api/prometheus/v1/api.go`, the method exposed by the client `LabelNames` doesn't allow the usage of the `start/end parameter`.

Is it something that can be changed ?

### PR DESCRIPTION
**Pull request by Nexucis**
fixes #766

### CODE REVIEW

**Comment by beorn7** [comment]
No worries about the go-1-10 CI failure, that's #765 .

**Comment by beorn7** [comment]
Thanks, everyone.

@Nexucis would you like to add start + name to `LabelValues` as suggested by @bwplotka ? I'll leave this PR open for a while in case you just want to add a commit here.

(And once this is in, it's time for a new release.)

**Comment by Nexucis** [comment]
Ah yes np I will modify the LabelValues as well

**Comment by Nexucis** [comment]
here we go, parameter added to `LabelValues` :)

**Comment by beorn7** [comment]
Thanks, but now we have a genuine test failure.

**Comment by Nexucis** [comment]
:O, I'm a genius lol. Sorry about that. It seems I was bit too fast on it. Will fix it

**Comment by Nexucis** [comment]
Looks better now @beorn7 , sorry for the mess. I mixed the query parameter and the path parameter

**Pull request merged**
