### PR TITLE
setup OSSF Scorecard workflow

### PR DESCRIPTION
**Pull request by mmorel-35**
Also pin github-actions versions

[OpenSSF Scorecard](https://securityscorecards.dev/viewer/?uri=github.com/prometheus/client_golang)

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by ArthurSens** [comment]
Hey 👋 -- thanks for the contribution.

Could you provide details about the OSSF scorecard and why we want to maintain it? Please assume I have no knowledge about what it is 😬

**Comment by mmorel-35** [comment]
Ossf is open source security foundation. The workflow is here to create a report that will help maintainers reduce security risk on their project with advices. See the badge I added in the description.

**Comment by ArthurSens** [comment]
I was taking a look at the report provided by the badge, I'm not sure I understood why we got 0 with Token-Permissions.

I don't guarantee that all permissions were configured following the least-privilege principle, but I'm pretty sure most of them are needed. Do we need to configure exceptions somewhere?

**Comment by ArthurSens** [comment]
This PR is also making changes to Dockerfile, which doesn't seem related to the OSSF scorecard, could we split it into a separate PR? It could make the merge process faster, at least for the Dockerfile changes

**Comment by mmorel-35** [comment]
It is related as ossf ask for dependencies to use pined version for docker as dor github-actions.

**Comment by ArthurSens** [comment]
> It is related as ossf ask for dependencies to use pinned version for docker as for github-actions. Please have a look here https://securityscorecards.dev/viewer/?uri=github.com/prometheus/client_golang
> 
> I’m fine seing this in a following pr

Yeah, I imagine that would be the reason :P I sust meant that the changes for the Dockerfile we could merge without problems already, so opening a separate PR would unblock this

For the OSSF scorecard, I'm still struggling to understand why we got a 0 score for github actions that need those permissions to run. I couldn't find ways to add exceptions for those checks 🤔

**Comment by kakkoyun** [comment]
> For the OSSF scorecard, I'm still struggling to understand why we got a 0 score for github actions that need those permissions to run. I couldn't find ways to add exceptions for those checks 🤔

@mmorel-35 Are there any quick wins that we could fix before putting this to the README?

**Pull request merged**
